version: '3.8'
services:
  api:
    container_name: express-api
    build:
      context: .
      dockerfile: Dockerfile-api-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/api
      - /usr/src/app/api/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=host.docker.internal
    depends_on:
      - db
  ui:
    build:
      context: .
      dockerfile: Dockerfile-ui-dev
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
      - ./client:/usr/src/app/ui
      - /usr/src/app/ui/node_modules
  db:
    container_name: db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    volumes:
      - ./data:/var/lib/postgresql/data
